#
# Central location for all ansible variables.  These are used in deployment,
# testing, and ansible based command-and-control (like backups).
#
deploy_user: ubuntu
deploy_home: /home/{{deploy_user}}/airflow
docker_pg_image: postgres:9.6
docker_airflow_image: puckel/docker-airflow:1.8.2
airflow_dags_home: "{{deploy_home}}/dags"
airflow_db_home: "{{deploy_home}}/db"
airflow_port: 8080
